-- Run this SQL in SQL Developer or SQL*Plus to extract package code
-- This will help us see what the package structure looks like

SET LONG 50000
SET LONGCHUNKSIZE 50000
SET PAGESIZE 0
SET LINESIZE 32767
SET TRIMSPOOL ON
SET FEEDBACK OFF
SET HEADING OFF

SPOOL PKG_LOAN_PROCESSOR_raw.sql

SELECT TEXT
FROM USER_SOURCE
WHERE NAME = 'PKG_LOAN_PROCESSOR'
  AND TYPE IN ('PACKAGE', 'PACKAGE BODY')
ORDER BY TYPE DESC, LINE;

SPOOL OFF

-- Also check if package exists
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME = 'PKG_LOAN_PROCESSOR'
ORDER BY OBJECT_TYPE;
