import random
import datetime as dt
import oracledb

USER = "app"
PASSWORD = "app"
DSN = "localhost:1521/FREEPDB1"

# ---------- helpers ----------
def exec_ddl(cur, sql):
    cur.execute(sql)

def drop_if_exists(cur, table):
    cur.execute("SELECT 1 FROM user_tables WHERE table_name = :t", t=table.upper())
    if cur.fetchone():
        print(f"↻ Dropping {table} …")
        cur.execute(f"DROP TABLE {table} CASCADE CONSTRAINTS PURGE")

def make_date(year, month, day):
    return dt.date(year, month, day)

# ---------- connect ----------
conn = oracledb.connect(user=USER, password=PASSWORD, dsn=DSN)
cur = conn.cursor()
print("✅ Connected to Oracle.")

# ---------- drop in FK-safe order ----------
tables = [
    "SALES_ORDER_ITEMS", "SALES_ORDERS",
    "SALARIES", "EMPLOYEES", "DEPARTMENTS", "STORES", "REGIONS",
    "PRODUCTS", "CATEGORIES",
    "CUSTOMERS"
]
for t in tables:
    drop_if_exists(cur, t)

# ---------- DDL ----------
print("🛠️  Creating tables …")

exec_ddl(cur, """
CREATE TABLE REGIONS (
  REGION_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  REGION_NAME   VARCHAR2(50) NOT NULL
)
""")

exec_ddl(cur, """
CREATE TABLE STORES (
  STORE_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  STORE_NAME    VARCHAR2(80) NOT NULL,
  REGION_ID     NUMBER NOT NULL,
  OPEN_DATE     DATE NOT NULL,
  CONSTRAINT FK_STORES_REGION FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID)
)
""")

exec_ddl(cur, """
CREATE TABLE DEPARTMENTS (
  DEPT_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  DEPT_NAME     VARCHAR2(60) NOT NULL
)
""")

exec_ddl(cur, """
CREATE TABLE EMPLOYEES (
  EMP_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  STORE_ID      NUMBER NOT NULL,
  DEPT_ID       NUMBER NOT NULL,
  FIRST_NAME    VARCHAR2(40) NOT NULL,
  LAST_NAME     VARCHAR2(40) NOT NULL,
  HIRE_DATE     DATE NOT NULL,
  EMAIL         VARCHAR2(120) UNIQUE,
  STATUS        VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT FK_EMP_STORE FOREIGN KEY (STORE_ID) REFERENCES STORES(STORE_ID),
  CONSTRAINT FK_EMP_DEPT  FOREIGN KEY (DEPT_ID)  REFERENCES DEPARTMENTS(DEPT_ID)
)
""")

exec_ddl(cur, """
CREATE TABLE SALARIES (
  SALARY_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  EMP_ID        NUMBER NOT NULL,
  EFFECTIVE_FROM DATE NOT NULL,
  EFFECTIVE_TO   DATE,
  BASE_SALARY   NUMBER(10,2) NOT NULL,
  CURRENCY      VARCHAR2(3) DEFAULT 'USD' NOT NULL,
  CONSTRAINT FK_SAL_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID)
)
""")

exec_ddl(cur, """
CREATE TABLE CUSTOMERS (
  CUST_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  FIRST_NAME    VARCHAR2(40) NOT NULL,
  LAST_NAME     VARCHAR2(40) NOT NULL,
  EMAIL         VARCHAR2(120) UNIQUE,
  PHONE         VARCHAR2(20),
  CREATED_AT    DATE DEFAULT SYSDATE NOT NULL
)
""")

exec_ddl(cur, """
CREATE TABLE CATEGORIES (
  CATEGORY_ID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  CATEGORY_NAME VARCHAR2(60) NOT NULL
)
""")

exec_ddl(cur, """
CREATE TABLE PRODUCTS (
  PRODUCT_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  CATEGORY_ID   NUMBER NOT NULL,
  SKU           VARCHAR2(30) UNIQUE NOT NULL,
  PRODUCT_NAME  VARCHAR2(120) NOT NULL,
  UNIT_PRICE    NUMBER(10,2) NOT NULL,
  ACTIVE        CHAR(1) DEFAULT 'Y' NOT NULL,
  CONSTRAINT FK_PROD_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
)
""")

exec_ddl(cur, """
CREATE TABLE SALES_ORDERS (
  ORDER_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ORDER_DATE    DATE NOT NULL,
  STORE_ID      NUMBER NOT NULL,
  EMP_ID        NUMBER,
  CUST_ID       NUMBER,
  ORDER_STATUS  VARCHAR2(20) DEFAULT 'COMPLETED' NOT NULL,
  CONSTRAINT FK_SO_STORE FOREIGN KEY (STORE_ID) REFERENCES STORES(STORE_ID),
  CONSTRAINT FK_SO_EMP   FOREIGN KEY (EMP_ID)   REFERENCES EMPLOYEES(EMP_ID),
  CONSTRAINT FK_SO_CUST  FOREIGN KEY (CUST_ID)  REFERENCES CUSTOMERS(CUST_ID)
)
""")

exec_ddl(cur, """
CREATE TABLE SALES_ORDER_ITEMS (
  ORDER_ITEM_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ORDER_ID      NUMBER NOT NULL,
  PRODUCT_ID    NUMBER NOT NULL,
  QTY           NUMBER(10,0) NOT NULL,
  UNIT_PRICE    NUMBER(10,2) NOT NULL,
  LINE_AMOUNT   NUMBER(12,2) GENERATED ALWAYS AS (QTY * UNIT_PRICE) VIRTUAL,
  CONSTRAINT FK_SOI_ORDER FOREIGN KEY (ORDER_ID)   REFERENCES SALES_ORDERS(ORDER_ID),
  CONSTRAINT FK_SOI_PROD  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
)
""")

# indexes for common lookups
exec_ddl(cur, "CREATE INDEX IX_EMP_STORE ON EMPLOYEES(STORE_ID)")
exec_ddl(cur, "CREATE INDEX IX_SAL_EMP ON SALARIES(EMP_ID, EFFECTIVE_FROM)")
exec_ddl(cur, "CREATE INDEX IX_PROD_CAT ON PRODUCTS(CATEGORY_ID)")
exec_ddl(cur, "CREATE INDEX IX_SO_STORE_DATE ON SALES_ORDERS(STORE_ID, ORDER_DATE)")
exec_ddl(cur, "CREATE INDEX IX_SOI_ORDER ON SALES_ORDER_ITEMS(ORDER_ID)")
conn.commit()

print("🌱 Seeding reference data …")

# ---------- seed reference ----------
regions = ["North", "South", "East", "West"]
cur.executemany("INSERT INTO REGIONS (REGION_NAME) VALUES (:1)", [(r,) for r in regions])

stores = []
open_base = dt.date(2022, 1, 1)
for i in range(1, 11):  # 10 stores
    stores.append((f"Store #{i:02d}", random.randint(1, len(regions)), open_base + dt.timedelta(days=random.randint(0, 800))))
cur.executemany("INSERT INTO STORES (STORE_NAME, REGION_ID, OPEN_DATE) VALUES (:1, :2, :3)", stores)

depts = ["Sales Floor", "Cashier", "Warehouse", "HR", "IT"]
cur.executemany("INSERT INTO DEPARTMENTS (DEPT_NAME) VALUES (:1)", [(d,) for d in depts])

categories = ["Grocery", "Electronics", "Home", "Clothing", "Toys"]
cur.executemany("INSERT INTO CATEGORIES (CATEGORY_NAME) VALUES (:1)", [(c,) for c in categories])
conn.commit()

print("👥 Seeding employees + salaries …")

# ---------- seed employees ----------
# fetch ids
cur.execute("SELECT STORE_ID FROM STORES")
store_ids = [r[0] for r in cur.fetchall()]
cur.execute("SELECT DEPT_ID FROM DEPARTMENTS")
dept_ids = [r[0] for r in cur.fetchall()]

first_names = ["Alex","Sam","Jordan","Taylor","Chris","Morgan","Jamie","Casey","Riley","Drew","Avery","Cameron"]
last_names  = ["Lee","Kim","Patel","Garcia","Nguyen","Brown","Davis","Wilson","Martinez","Clark","Lopez","Walker"]

emp_rows = []
today = dt.date.today()
for _ in range(30):  # ~30 employees
    fn = random.choice(first_names)
    ln = random.choice(last_names)
    store_id = random.choice(store_ids)
    dept_id  = random.choice(dept_ids)
    hire = today - dt.timedelta(days=random.randint(30, 1200))
    email = f"{fn}.{ln}{random.randint(100,999)}@example.com".lower()
    emp_rows.append((store_id, dept_id, fn, ln, hire, email, "ACTIVE"))

cur.executemany("""
INSERT INTO EMPLOYEES (STORE_ID, DEPT_ID, FIRST_NAME, LAST_NAME, HIRE_DATE, EMAIL, STATUS)
VALUES (:1,:2,:3,:4,:5,:6,:7)
""", emp_rows)
conn.commit()

# salaries: 1–2 effective rows per employee
cur.execute("SELECT EMP_ID FROM EMPLOYEES")
emp_ids = [r[0] for r in cur.fetchall()]
sal_rows = []
for emp in emp_ids:
    start = today - dt.timedelta(days=random.randint(200, 1200))
    base = random.randint(32000, 80000)
    sal_rows.append((emp, start, None, float(base), 'USD'))
    if random.random() < 0.4:  # 40% have a raise
        mid = start + dt.timedelta(days=random.randint(90, 400))
        sal_rows[-1] = (emp, start, mid - dt.timedelta(days=1), float(base), 'USD')
        sal_rows.append((emp, mid, None, float(base + random.randint(1000, 8000)), 'USD'))

cur.executemany("""
INSERT INTO SALARIES (EMP_ID, EFFECTIVE_FROM, EFFECTIVE_TO, BASE_SALARY, CURRENCY)
VALUES (:1,:2,:3,:4,:5)
""", sal_rows)
conn.commit()

print("🧑‍🤝‍🧑 Seeding customers …")
cust_rows = []
for i in range(100):
    fn = random.choice(first_names)
    ln = random.choice(last_names)
    email = f"{fn}.{ln}{i:03d}@custmail.com".lower()
    phone = f"+1-555-{random.randint(100,999)}-{random.randint(1000,9999)}"
    created = today - dt.timedelta(days=random.randint(1, 800))
    cust_rows.append((fn, ln, email, phone, created))
cur.executemany("""
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE, CREATED_AT)
VALUES (:1,:2,:3,:4,:5)
""", cust_rows)
conn.commit()

print("📦 Seeding products …")
# fetch categories
cur.execute("SELECT CATEGORY_ID FROM CATEGORIES")
cat_ids = [r[0] for r in cur.fetchall()]
prod_rows = []
for i in range(50):  # ~50 products
    cat = random.choice(cat_ids)
    sku = f"SKU-{i+1:04d}"
    name = f"Product {i+1:03d}"
    price = round(random.uniform(3.0, 600.0), 2)
    active = 'Y' if random.random() > 0.05 else 'N'
    prod_rows.append((cat, sku, name, price, active))
cur.executemany("""
INSERT INTO PRODUCTS (CATEGORY_ID, SKU, PRODUCT_NAME, UNIT_PRICE, ACTIVE)
VALUES (:1,:2,:3,:4,:5)
""", prod_rows)
conn.commit()

print("🧾 Seeding sales orders + items …")
# fetch ids needed
cur.execute("SELECT PRODUCT_ID, UNIT_PRICE FROM PRODUCTS WHERE ACTIVE='Y'")
prod_price = cur.fetchall()
cur.execute("SELECT CUST_ID FROM CUSTOMERS")
cust_ids = [r[0] for r in cur.fetchall()]
cashiers = emp_ids  # any employee can ring sales in this demo

order_rows = []
item_rows = []

num_orders = 200
for _ in range(num_orders):
    order_date = today - dt.timedelta(days=random.randint(0, 180))
    store_id = random.choice(store_ids)
    emp_id = random.choice(cashiers)
    cust_id = random.choice(cust_ids) if random.random() > 0.1 else None  # some walk-ins
    status = "COMPLETED"
    order_rows.append((order_date, store_id, emp_id, cust_id, status))

# insert orders, retrieve generated ids
cur.executemany("""
INSERT INTO SALES_ORDERS (ORDER_DATE, STORE_ID, EMP_ID, CUST_ID, ORDER_STATUS)
VALUES (:1,:2,:3,:4,:5)
""", order_rows)
conn.commit()

cur.execute("SELECT ORDER_ID FROM SALES_ORDERS ORDER BY ORDER_ID")
order_ids = [r[0] for r in cur.fetchall()]

for oid in order_ids:
    for _ in range(random.randint(1, 5)):  # 1–5 line items per order
        product_id, unit_price = random.choice(prod_price)
        qty = random.randint(1, 5)
        item_rows.append((oid, product_id, qty, float(unit_price)))

cur.executemany("""
INSERT INTO SALES_ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QTY, UNIT_PRICE)
VALUES (:1,:2,:3,:4)
""", item_rows)
conn.commit()

print("\n📊 Quick counts:")
for name, sql in [
    ("REGIONS", "SELECT COUNT(*) FROM REGIONS"),
    ("STORES", "SELECT COUNT(*) FROM STORES"),
    ("DEPARTMENTS", "SELECT COUNT(*) FROM DEPARTMENTS"),
    ("EMPLOYEES", "SELECT COUNT(*) FROM EMPLOYEES"),
    ("SALARIES", "SELECT COUNT(*) FROM SALARIES"),
    ("CUSTOMERS", "SELECT COUNT(*) FROM CUSTOMERS"),
    ("CATEGORIES", "SELECT COUNT(*) FROM CATEGORIES"),
    ("PRODUCTS", "SELECT COUNT(*) FROM PRODUCTS"),
    ("SALES_ORDERS", "SELECT COUNT(*) FROM SALES_ORDERS"),
    ("SALES_ORDER_ITEMS", "SELECT COUNT(*) FROM SALES_ORDER_ITEMS"),
]:
    cur.execute(sql)
    print(f"  - {name:18s}: {cur.fetchone()[0]}")

cur.close()
conn.close()
print("\n✅ Retail schema created and seeded.")
